/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ComponentButton {
        /**
          * Button text
         */
        "text": string;
        /**
          * Used to specify a type of the button. Can be "primary" or "secondary"
         */
        "type": string;
    }
}
declare global {
    interface HTMLComponentButtonElement extends Components.ComponentButton, HTMLStencilElement {
    }
    var HTMLComponentButtonElement: {
        prototype: HTMLComponentButtonElement;
        new (): HTMLComponentButtonElement;
    };
    interface HTMLElementTagNameMap {
        "component-button": HTMLComponentButtonElement;
    }
}
declare namespace LocalJSX {
    interface ComponentButton {
        /**
          * Button text
         */
        "text"?: string;
        /**
          * Used to specify a type of the button. Can be "primary" or "secondary"
         */
        "type"?: string;
    }
    interface IntrinsicElements {
        "component-button": ComponentButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "component-button": LocalJSX.ComponentButton & JSXBase.HTMLAttributes<HTMLComponentButtonElement>;
        }
    }
}
