/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ComponentButton {
        /**
          * Button text
         */
        "text": string;
        /**
          * Used to specify a type of the button. Can be "primary" or "secondary"
         */
        "type": string;
    }
    interface ComponentInput {
        /**
          * Type of this input field it can be email, number, text, password etc.
         */
        "inputType": string;
        /**
          * Text for the label that shows above input field
         */
        "labelText": string;
        /**
          * Text that is used as a placeholder for the input field
         */
        "placeholderText": string;
    }
}
declare global {
    interface HTMLComponentButtonElement extends Components.ComponentButton, HTMLStencilElement {
    }
    var HTMLComponentButtonElement: {
        prototype: HTMLComponentButtonElement;
        new (): HTMLComponentButtonElement;
    };
    interface HTMLComponentInputElement extends Components.ComponentInput, HTMLStencilElement {
    }
    var HTMLComponentInputElement: {
        prototype: HTMLComponentInputElement;
        new (): HTMLComponentInputElement;
    };
    interface HTMLElementTagNameMap {
        "component-button": HTMLComponentButtonElement;
        "component-input": HTMLComponentInputElement;
    }
}
declare namespace LocalJSX {
    interface ComponentButton {
        /**
          * Button text
         */
        "text"?: string;
        /**
          * Used to specify a type of the button. Can be "primary" or "secondary"
         */
        "type"?: string;
    }
    interface ComponentInput {
        /**
          * Type of this input field it can be email, number, text, password etc.
         */
        "inputType"?: string;
        /**
          * Text for the label that shows above input field
         */
        "labelText"?: string;
        /**
          * Text that is used as a placeholder for the input field
         */
        "placeholderText"?: string;
    }
    interface IntrinsicElements {
        "component-button": ComponentButton;
        "component-input": ComponentInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "component-button": LocalJSX.ComponentButton & JSXBase.HTMLAttributes<HTMLComponentButtonElement>;
            "component-input": LocalJSX.ComponentInput & JSXBase.HTMLAttributes<HTMLComponentInputElement>;
        }
    }
}
